### ISSUE TITLE
Can't make GLAMER on ubuntu 14.04

### ISSUE THREAD

**Issue by khharut** [glenco/glamer#11]
Hi,

I can not make this project on my ubuntu machine. It said 

CMake Error at CMakeLists.txt:64 (export):
  export given target "NR" which is not built by this project.

And actually there is no NR github project to clone.

Regards, Harutyun

**Comment by rbmetcalf** [comment]
Are you sure you are signed into GiHub?  NR is a private repository, but 
as a member of the team you should be able to see and download it.  
I'll double check on it.

**Comment by khharut** [comment]
Thanks.
