### ISSUE TITLE
High-z pixel maps

### ISSUE THREAD

**Issue by TiagoBsCastro** [glenco/glamer#13]
Hi guys,

  I was facing some problems to ray-trace high-z pixel-maps and I figured out that it was due to the readMap routine in MOKAfits.cpp that interpolates angular distances up to z=5 only. Is there a reason to that --- like some routine that doesn't work from this point forward? If not, wouldn't it be more reasonable to put a very high-z value for this interpolation?

**Comment by cgiocoli** [comment]
Absolutely, it was initially set like this because my light-cones where going only up to z=4.

**Comment by rbmetcalf** [comment]
The angular size distance should be coming from the COSMOLOGY class which interpolates it internally to make it fast up to z=10 and then calculates by numerical integration if it is call for a higher redshift.
I am not sure why this is happening in MOKAfits.cpp  We will have to fix it.

**Comment by rbmetcalf** [comment]
Do you think this happens on line 239?

**Comment by rbmetcalf** [comment]
I have made a pull request (#130) for SLsimLib that should solve this.
Check that out and see if it has any problems.  This conversations 
should move to that PR.

**Comment by TiagoBsCastro** [comment]
Hi guys, 

I don't see any PR.
@rbmetcalf I think the kernel of the problem is line 228
          Utilities::fill_linear(zi,ni,0.,5.); // max redshift should be around 2.5!
          for(int i=0;i<ni;i++) dli[i] = cosmo.angDist(zi[i])*(1+zi[i]);

**Comment by rbmetcalf** [comment]
The PR is in the SLsimLib project and not in this GLAMER project (https://github.com/glenco/SLsimLib/pull/130).  I've been meaning to merge 
the projects for some time, but for now you will need to pull that project and CosmoLib
